services:
  - type: web
    name: otto-api
    runtime: node
    plan: free
    autoDeploy: true
    buildCommand: "npm install"
    startCommand: "node server.cjs"
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PORT
        value: 3001
      - key: DB_HOST
        value: 35.214.224.135
      - key: DB_USER
        value: uwcw1gm1sor8u
      - key: DB_PASSWORD
        value: g05jkizfzjdp
      - key: DB_NAME
        value: db6ctx4kvleywe
